error[E0507]: cannot move out of index of `HashMap<std::string::String, Entity>`   --> src/scenarios/dating_prob2.rs:66:27    | 66 |         let jack_entity = domain_entity_map[&Domain::Jack.to_string()];    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    |                           |    |                           move occurs because value has type `Entity`, which does not implement the `Copy` trait    |                           help: consider borrowing here: `&domain_entity_map[&Domain::Jack.to_string()]`