error[E0412]: cannot find type `ImplicationInstance` in this scope   --> src/common/model.rs:38:24    | 37 | pub struct  Factor {    |                   - help: you might be missing a type parameter: `<ImplicationInstance>` 38 |     pub conjuncts: Vec<ImplicationInstance>,    |                        ^^^^^^^^^^^^^^^^^^^ not found in this scope
error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/model/maxent.rs:61:60
    |
61  |             debug!("Generated unique key for feature: {}", feature);
    |                                                            ^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
note: required by a bound in `ArgumentV1::<'a>::new_display`
   --> /Users/greg/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:345:5
    |
345 |     arg_new!(new_display, Display);