error[E0382]: use of moved value: `fact_memory`    --> src/common/test.rs:113:47     | 106 |     let fact_memory = EmptyFactDB::new_shared(&resources.redis)?;     |         ----------- move occurs because `fact_memory` has type `Rc<dyn PropositionDB>`, which does not implement the `Copy` trait ... 110 |         Inferencer::new_mutable(model.clone(), proposition_graph.clone(), fact_memory)?;     |                                                                           ----------- value moved here ... 113 |     let mut repl = ReplState::new(inferencer, fact_memory);     |                                               ^^^^^^^^^^^ value used here after move