good but needs to run the print loop
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/inference/lambda.rs:94:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:775:21
   4: bayes_star::inference::lambda::<impl bayes_star::inference::inference::Inferencer>::lambda_send_single
             at ./src/inference/lambda.rs:91:34
   5: bayes_star::inference::lambda::<impl bayes_star::inference::inference::Inferencer>::lambda_send_generic
             at ./src/inference/lambda.rs:69:17
   6: bayes_star::inference::lambda::<impl bayes_star::inference::inference::Inferencer>::lambda_visit_node
             at ./src/inference/lambda.rs:62:9
   7: bayes_star::inference::lambda::<impl bayes_star::inference::inference::Inferencer>::do_lambda_traversal
             at ./src/inference/lambda.rs:12:13
   8: bayes_star::inference::inference::Inferencer::initialize
             at ./src/inference/inference.rs:91:9
   9: bayes_star::inference::inference::inference_compute_marginals
             at ./src/inference/inference.rs:235:5
  10: bayes_star::common::test::do_testing
             at ./src/common/test.rs:19:9
  11: test::main
             at ./src/bin/test.rs:12:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5