it's crashing here
thread '<unnamed>' panicked at src/explorer/routes/experiment_route.rs:69:54:
called `Result::unwrap()` on an `Err` value: Error("missing field `relation`", line: 1, column: 112)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/result.rs:1077:23
   4: bayes_star::explorer::routes::experiment_route::render_implication_part
             at ./src/explorer/routes/experiment_route.rs:69:25
   5: bayes_star::explorer::routes::experiment_route::render_experiment_parts
             at ./src/explorer/routes/experiment_route.rs:86:28
   6: bayes_star::explorer::routes::experiment_route::internal_experiment
             at ./src/explorer/routes/experiment_route.rs:110:21
   7: explorer_server::experiment
             at ./src/bin/explorer_server.rs:37:5
   8: explorer_server::rocket_route_fn_experiment
             at ./src/bin/explorer_server.rs:36:4
   9: core::ops::function::Fn::call
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/ops/function.rs:79:5
  10: <F as rocket::handler::Handler>::handle
             at /Users/greg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket-0.