error[E0063]: missing field `proposition_graph` in initializer of `Inferencer`   --> src/inference/inference.rs:39:12    | 39 |         Ok(Inferencer {    |            ^^^^^^^^^^ missing `proposition_graph`
For more information about this error, try `rustc --explain E0063`.