runs but crashes in test with
[2024-01-05T00:07:06Z INFO  bayes_star::model::conjunction] Calculating conjunction probability for a conjunction with 1 terms
[2024-01-05T00:07:06Z INFO  bayes_star::model::conjunction] Getting proposition probability for term 0: Proposition { roles: [FilledRole { role_name: "subject", argument: Constant(ConstantArgument { domain: Jack, entity_id: "test_Jack0" }) }, FilledRole { role_name: "relation", argument: Constant(ConstantArgument { domain: Verb, entity_id: "like" }) }, FilledRole { role_name: "object", argument: Constant(ConstantArgument { domain: Jill, entity_id: "test_Jill0" }) }] }
thread 'main' panicked at '`term_prob` should be Some here.', src/model/conjunction.rs:17:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1880:5
   5: core::option::Option<T>::expect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:738:21
   6: bayes_star::model::conjunction::get_conjunction_probability
             at ./src/model/conjunction.rs:17:33
   7: bayes_star::model::maxent::features_from_backlinks
             at ./src/model/maxent.rs:47:15
   8: bayes_star::model::inference::inference_probability
             at ./src/model/inference.rs:58:26
   9: bayes_star::main
             at ./src/main.rs:69:32