this error
[2024-01-04T16:33:11Z TRACE bayes_star::model::maxent] train_on_example - Error in features_from_backlinks: Response was of incompatible type - TypeError: "Response type not string compatible." (response was nil)
thread 'main' panicked at 'do_training - Error in train_on_example for proposition 0 Proposition { roles: [FilledRole { role_name: "subject", argument: Constant(ConstantArgument { domain: Jack, entity_id: "Jack20" }) }, FilledRole { role_name: "relation", argument: Constant(ConstantArgument { domain: Verb, entity_id: "date" }) }, FilledRole { role_name: "object", argument: Constant(ConstantArgument { domain: Jill, entity_id: "Jill12" }) }] }: Response was of incompatible type - TypeError: "Response type not string compatible." (response was nil)', src/model/maxent.rs:160:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: bayes_star::model::maxent::do_training
             at ./src/model/maxent.rs:160:17
   3: bayes_star::main
             at ./src/main.rs:59:24
   4: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5