BAYES STAR Config { entities_per_domain: 32, print_training_loss: false } [2024-01-04T16:44:06Z ERROR bayes_star::model::maxent] Error computing conjunction probability for backlink 0: Response was of incompatible type - TypeError: "Response type not string compatible." (response was nil) thread 'main' panicked at 'do_training - Error in train_on_example for proposition 1 Proposition { roles: [FilledRole { role_name: "subject", argument: Constant(ConstantArgument { domain: Jack, entity_id: "Jack4" }) }, FilledRole { role_name: "relation", argument: Constant(ConstantArgument { domain: Verb, entity_id: "date" }) }, FilledRole { role_name: "object", argument: Constant(ConstantArgument { domain: Jill, entity_id: "Jill14" }) }] }: Response was of incompatible type - TypeError: "Response type not string compatible." (response was nil)', src/model/maxent.rs:176:17 stack backtrace: