next error error[E0277]: `objects::FirstOrderArgument` doesn't implement `std::fmt::Display`    --> src/model/objects.rs:198:56     | 198 |             .map(|(key, value)| format!("{}: {}", key, value)) // Assuming FirstOrderArgument implements Display     |                                                        ^^^^^ `objects::FirstOrderArgument` cannot be formatted with the default formatter     |