need to remove the use of the weight feature
    }
  }
}
/Users/greg/Code/bayes2/node/model/maxent.js:21
    const pwr = WeightRecord({ feature: PositiveFeature(feature), weight })
                ^

ReferenceError: WeightRecord is not defined
    at InitializeWeights (/Users/greg/Code/bayes2/node/model/maxent.js:21:17)
    at main (/Users/greg/Code/bayes2/node/model/train.js:14:15)