hmm
error[E0502]: cannot borrow `*self` as mutable because it is also borrowed as immutable
  --> src/inference/inference.rs:56:13
   |
55 |         for root in &self.proposition_graph.roots {
   |                     -----------------------------
   |                     |
   |                     immutable borrow occurs here
   |                     immutable borrow later used here
56 |             self.initialize_pi_proposition(root, true)?;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here

error[E0502]: cannot borrow `*self` as mutable because it is also borrowed as immutable
  --> src/inference/inference.rs:68:13
   |
66 |         let children = self.proposition_graph.get_single_forward(node);
   |                        ----------------------------------------------- immutable borrow occurs here
67 |         for child in children {
   |                      -------- a temporary with access to the immutable borrow is created here ...
68 |             self.initialize_pi_conjunct(child, false)?;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
69 |         }
   |         - ... and the immutable borrow might be used here, when that temporary is dropped and runs the destructor for type `impl Iterator<Item = &PropositionGroup>`