Checking bayes-star v0.1.0 (/Users/greg/Code/bayes-star/rust) error[E0449]: unnecessary visibility qualifier   --> src/scenarios/dating_prob2.rs:33:5    | 33 |     pub fn setup_scenario(storage: &mut Storage) -> Result<(), Box<dyn Error>> {    |     ^^^ `pub` not permitted here because it's implied
error[E0405]: cannot find trait `ScenarioMaker` in this scope
  --> src/scenarios/dating_prob2.rs:32:6
   |
32 | impl ScenarioMaker for DatingProb2 {
   |      ^^^^^^^^^^^^^ not found in this scope
   |
note: trait `crate::common::run::ScenarioMaker` exists but is inaccessible
  --> src/common/run.rs:7:1
   |
7  | pub trait ScenarioMaker {
   | ^^^^^^^^^^^^^^^^^^^^^^^ not accessible