error[E0599]: no function or associated item named `new` found for struct `GraphicalModel` in the current scope   --> src/common/run.rs:76:39    | 76 |     let mut storage = GraphicalModel::new(connection).expect("Couldn't make storage");    |                                       ^^^ function or associated item not found in `GraphicalModel`    |