backward links is broken
running 1 test
test test_get_predicate_backward_links ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `premise`", line: 1, column: 179)', tests/predicate_graph_tests.rs:164:71
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAILED

failures:

failures:
    test_get_predicate_backward_links