stuck here
error[E0502]: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/inference/inference.rs:115:21
    |
113 |         for node in &self.bfs_order {
    |                     ---------------
    |                     |
    |                     immutable borrow occurs here
    |                     immutable borrow later used here
114 |             print_yellow!("send pi bfs selects {:?}", node);
115 |             let _ = self.pi_visit_node(node)?;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here