error[E0425]: cannot find value `CONFIG` in this scope   --> src/scenarios/dating_simple.rs:45:22    | 45 |         let config = CONFIG.get().expect("Config not initialized");    |                      ^^^^^^ not found in this scope
error[E0308]: mismatched types
  --> src/common/run.rs:21:50
   |
21 |     let mut factor_model = ExponentialModel::new(redis)?;
   |                            --------------------- ^^^^^ expected struct `FactoryResources`, found struct `RedisManager`
   |                            |
   |                            arguments to this function are incorrect
   |
   = note: expected reference `&FactoryResources`
              found reference `&RedisManager`
note: associated function defined here
  --> src/model/maxent.rs:24:12
   |
24 |     pub fn new(resources: &FactoryResources) -> Result<Box<dyn FactorModel>, Box<dyn Error>> {
   |            ^^^ ----------------------------