error[E0596]: cannot borrow `*lambda_values` as mutable, as it is behind a `&` reference    --> src/bp/bptable.rs:137:35     | 113 |         lambda_values: &HashMap<(String, usize), f64>,     |                        ------------------------------ help: consider changing this to be a mutable reference: `&mut HashMap<(std::string::String, usize), f64>` ... 137 |             if let Some(lambda) = lambda_values.get_mut(&lambda_key) {     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `lambda_values` is a `&` reference, so the data it refers to cannot be borrowed as mutable
error[E0596]: cannot borrow `*lambda_values` as mutable, as it is behind a `&` reference
   --> src/bp/bptable.rs:143:17
    |
113 |         lambda_values: &HashMap<(String, usize), f64>,
    |                        ------------------------------ help: consider changing this to be a mutable reference: `&mut HashMap<(std::string::String, usize), f64>`
...
143 |                 lambda_values.insert(lambda_key, to_lambda);
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `lambda_values` is a `&` reference, so the data it refers to cannot be borrowed as mutable