error[E0596]: cannot borrow data in an `Rc` as mutable   --> src/common/test.rs:63:9    | 63 |         self.fact_memory.store_proposition_probability(&prop, new_prob);    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable    |    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Rc<dyn PropositionDB>`