need to fix 2 now
error[E0061]: this method takes 4 arguments but 3 arguments were supplied
   --> src/inference/pi.rs:97:38
    |
97  |             let true_marginal = self.score_factor_assignment(&parent_nodes, combination, node)?;
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^ ------------- an argument of type `&mut redis::Connection` is missing
    |
note: method defined here
   --> src/inference/inference.rs:214:12
    |
214 |     pub fn score_factor_assignment(
    |            ^^^^^^^^^^^^^^^^^^^^^^^
215 |         &self,