error[E0502]: cannot borrow `*self` as mutable because it is also borrowed as immutable   --> src/inference/inference.rs:56:13    | 55 |         for root in &self.proposition_graph.roots {    |                     -----------------------------    |                     |    |                     immutable borrow occurs here    |                     immutable borrow later used here 56 |             self.initialize_pi_proposition(root, true)?;    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
error[E0502]: cannot borrow `*self` as mutable because it is also borrowed as immutable
   --> src/inference/inference.rs:134:13
    |
132 |         let roots = self.proposition_graph.get_roots();
    |                     ---------------------------------- immutable borrow occurs here
133 |         for root in roots {
    |                     ----- a temporary with access to the immutable borrow is created here ...
134 |             self.initialize_lambda_proposition(root)?;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
135 |         }
    |         - ... and the immutable borrow might be used here, when that temporary is dropped and runs the destructor for type `impl Iterator<Item = &objects::Proposition>`