error[E0425]: cannot find value `file_name` in this scope    --> src/inference/inference.rs:133:19     | 133 |             .open(file_name)?;     |                   ^^^^^^^^^ not found in this scope
error[E0063]: missing field `marginal_output_file` in initializer of `ConfigurationOptions`
  --> src/common/setup.rs:68:5
   |
68 |     ConfigurationOptions {
   |     ^^^^^^^^^^^^^^^^^^^^ missing `marginal_output_file`