[2024-01-04T16:33:11Z TRACE bayes_star::model::maxent] train_on_example - Start: Proposition { roles: [FilledRole { role_name: "subject", argument: Constant(ConstantArgument { domain: Jack, entity_id: "Jack20" }) }, FilledRole { role_name: "relation", argument: Constant(ConstantArgument { domain: Verb, entity_id: "date" }) }, FilledRole { role_name: "object", argument: Constant(ConstantArgument { domain: Jill, entity_id: "Jill12" }) }] } [2024-01-04T16:33:11Z TRACE bayes_star::model::maxent] train_on_example - Getting features from backlinks [2024-01-04T16:33:11Z TRACE bayes_star::model::maxent] train_on_example - Error in features_from_backlinks: Response was of incompatible type - TypeError: "Response type not string compatible." (response was nil) thread 'main' panicked at 'do_training - Error in train_on_example for proposition 0 Proposition { roles: [FilledRole { role_name: "subject", argument: Constant(ConstantArgument { domain: Jack, entity_id: "Jack20" }) }, FilledRole { role_name: "relation", argument: Constant(ConstantArgument { domain: Verb, entity_id: "date" }) }, FilledRole { role_name: "object", argument: Constant(ConstantArgument { domain: Jill, entity_id: "Jill12" }) }] }: Response was of incompatible type - TypeError: "Response type not string compatible." (response was nil)', src/model/maxent.rs:160:17 stack backtrace: