something is missing in the probability table
greg@Gregs-MacBook-Pro-2 node % ./dotrain.sh
/Users/greg/Code/bayes_star/node/model/maxent.js:39
    const r = record.probability
                     ^

TypeError: Cannot read properties of null (reading 'probability')
    at GetPropositionProbability (/Users/greg/Code/bayes_star/node/model/maxent.js:39:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FeaturesFromBacklinks (/Users/greg/Code/bayes_star/node/model/maxent.js:71:29)
    at async TrainOnExample (/Users/greg/Code/bayes_star/node/model/maxent.js:139:22)
    at async main (/Users/greg/Code/bayes_star/node/model/train.js:20:9)

Node.js v21.1.0