error[E0507]: cannot move out of `model.graph` which is behind a mutable reference   --> src/scenarios/dating_prob2.rs:33:23    | 33 |         let storage = model.graph;    |                       ^^^^^^^^^^^    |                       |    |                       move occurs because `model.graph` has type `Graph`, which does not implement the `Copy` trait    |                       help: consider borrowing here: `&model.graph`
error[E0596]: cannot borrow `storage` as mutable, as it is not declared as mutable
  --> src/scenarios/dating_prob2.rs:34:9
   |
33 |         let storage = model.graph;
   |             ------- help: consider changing this to be mutable: `mut storage`
34 |         storage.drop_all_dbs().map_err(|e| e.to_string())?;
   |         ^^^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable

error[E0596]: cannot borrow `storage` as mutable, as it is not declared as mutable
  --> src/scenarios/dating_prob2.rs:65:17
   |
33 |         let storage = model.graph;
   |             ------- help: consider changing this to be mutable: `mut storage`
...