error[E0063]: missing field `mapping` in initializer of `MarginalTable`    --> src/inference/inference.rs:163:21     | 163 |         let table = MarginalTable { entries };     |                     ^^^^^^^^^^^^^ missing `mapping`
error[E0063]: missing field `mapping` in initializer of `MarginalTable`
   --> src/inference/inference.rs:186:21
    |
186 |         let table = MarginalTable { entries };
    |                     ^^^^^^^^^^^^^ missing `mapping`

For more information about this error, try `rustc --explain E0063`.