error[E0596]: cannot borrow `*storage` as mutable, as it is behind a `&` reference   --> src/model/choose.rs:93:28    | 75 |     storage: &Storage,    |              -------- help: consider changing this to be a mutable reference: `&mut Storage` ... 93 |         let implications = storage.find_premises(&search_key)?;    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `storage` is a `&` reference, so the data it refers to cannot be borrowed as mutable
error[E0596]: cannot borrow `*storage` as mutable, as it is behind a `&` reference
  --> src/common/run.rs:14:24
   |
12 | pub fn do_training(model:Box<dyn LogicalModel>, storage: &Storage) -> Result<(), Box<dyn Error>> {
   |                                                          -------- help: consider changing this to be a mutable reference: `&mut Storage`
13 |     trace!("do_training - Getting all implications");
14 |     let implications = storage.get_all_implications()?;
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `storage` is a `&` reference, so the data it refers to cannot be borrowed as mutable

error[E0596]: cannot borrow `*model` as mutable, as `model` is not declared as mutable
  --> src/common/run.rs:17:9
   |
12 | pub fn do_training(model:Box<dyn LogicalModel>, storage: &Storage) -> Result<(), Box<dyn Error>> {
   |                    ----- help: consider changing this to be mutable: `mut model`
...
17 |         model.initialize_connection( &implication)?;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable