error[E0507]: cannot move out of `proposition.predicate.function` which is behind a shared reference   --> src/model/ops.rs:21:20    | 21 |     Predicate::new(proposition.predicate.function, result)    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `proposition.predicate.function` has type `std::string::String`, which does not implement the `Copy` trait
error[E0507]: cannot move out of `predicate.function` which is behind a shared reference
  --> src/model/ops.rs:66:20
   |
66 |     let function = predicate.function;
   |                    ^^^^^^^^^^^^^^^^^^
   |                    |
   |                    move occurs because `predicate.function` has type `std::string::String`, which does not implement the `Copy` trait
   |                    help: consider borrowing here: `&predicate.function`