need to get the scednario name!...
that's cool

greg@192 rust % ./explorer.sh
   Compiling bayes-star v0.1.0 (/Users/greg/Code/bayes-star/rust)
    Finished dev [unoptimized + debuginfo] target(s) in 2.78s
     Running `target/debug/explorer_server`
error: The following required arguments were not provided:
    --scenario_name <STRING>

USAGE:
    explorer_server [OPTIONS] --scenario_name <STRING>

For more information try --help