error[E0046]: not all trait items implemented, missing: `initialize_connection`, `predict`    --> src/model/maxent.rs:136:1     | 136 |   impl LogicalModel for ExponentialModel {     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `initialize_connection`, `predict` in implementation     |    ::: src/common/interface.rs:20:5     | 20  |       fn initialize_connection(&mut self, implication:&Implication) -> Result<(), Box<dyn Error>>;     |       -------------------------------------------------------------------------------------------- `initialize_connection` from trait ... 28  | /     fn predict( 29  | |         &self, 30  | |         storage: &Storage, 31  | |         evidence: &dyn PropositionProbability, 32  | |         proposition: &Proposition, 33  | |     ) -> Result<PredictStatistics, Box<dyn Error>>;     | |___________________________________________________- `predict` from trait