error[E0449]: unnecessary visibility qualifier   --> src/common/fact_db.rs:62:5    | 62 |     pub fn store_proposition_probability(    |     ^^^ `pub` not permitted here because it's implied
error[E0046]: not all trait items implemented, missing: `store_proposition_probability`
  --> src/model/inference.rs:90:1
   |
90 |   impl FactDB for MapBackedProbabilityStorage {
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `store_proposition_probability` in implementation
   |
  ::: src/common/interface.rs:20:5
   |
20 | /     fn store_proposition_probability(
21 | |         &mut self,
22 | |         proposition: &Proposition,
23 | |         probability: f64,
24 | |     ) -> Result<(), Box<dyn Error>>;
   | |____________________________________- `store_proposition_probability` from trait

error[E0599]: no method named `store_proposition` found for struct `Graph` in the current scope
  --> src/scenarios/dating_prob2.rs:87:29
   |
87 |                 model.graph.store_proposition(&jack_lonely, p_jack_lonely)?;
   |                             ^^^^^^^^^^^^^^^^^ method not found in `Graph`
   |
  ::: src/common/graph.rs:17:1
   |
17 | pub struct Graph {
   | ---------------- method `store_proposition` not found for this struct

error[E0599]: no method named `store_proposition` found for struct `Graph` in the current scope
  --> src/scenarios/dating_prob2.rs:99:29
   |
99 |                 model.graph.store_proposition(&jill_exciting, p_jill_exciting)?;
   |                             ^^^^^^^^^^^^^^^^^ method not found in `Graph`
   |
  ::: src/common/graph.rs:17:1
   |
17 | pub struct Graph {
   | ---------------- method `store_proposition` not found for this struct

error[E0599]: no method named `store_proposition` found for struct `Graph` in the current scope
   --> src/scenarios/dating_prob2.rs:117:29
    |
117 |                 model.graph.store_proposition(&jill_likes_jack, p_jill_likes_jack)?;
    |                             ^^^^^^^^^^^^^^^^^ method not found in `Graph`
    |
   ::: src/common/graph.rs:17:1
    |
17  | pub struct Graph {
    | ---------------- method `store_proposition` not found for this struct

error[E0599]: no method named `store_proposition` found for struct `Graph` in the current scope
   --> src/scenarios/dating_prob2.rs:134:33
    |
134 |                     model.graph.store_proposition(&jack_likes_jill, p_jack_likes_jill)?;
    |                                 ^^^^^^^^^^^^^^^^^ method not found in `Graph`
    |
   ::: src/common/graph.rs:17:1
    |
17  | pub struct Graph {
    | ---------------- method `store_proposition` not found for this struct

error[E0599]: no method named `maybe_add_to_training` found for struct `Graph` in the current scope
   --> src/scenarios/dating_prob2.rs:136:29
    |
136 |                 model.graph.maybe_add_to_training(is_training, &jack_likes_jill)?;
    |                             ^^^^^^^^^^^^^^^^^^^^^ method not found in `Graph`
    |
   ::: src/common/graph.rs:17:1
    |
17  | pub struct Graph {
    | ---------------- method `maybe_add_to_training` not found for this struct

error[E0599]: no method named `store_proposition` found for struct `Graph` in the current scope
   --> src/scenarios/dating_prob2.rs:153:29
    |
153 |                 model.graph.store_proposition(&jack_dates_jill, effective_p)?;
    |                             ^^^^^^^^^^^^^^^^^ method not found in `Graph`
    |
   ::: src/common/graph.rs:17:1
    |
17  | pub struct Graph {
    | ---------------- method `store_proposition` not found for this struct

error[E0599]: no method named `maybe_add_to_training` found for struct `Graph` in the current scope
   --> src/scenarios/dating_prob2.rs:154:29
    |
154 |                 model.graph.maybe_add_to_training(is_training, &jack_dates_jill)?;
    |                             ^^^^^^^^^^^^^^^^^^^^^ method not found in `Graph`
    |
   ::: src/common/graph.rs:17:1
    |
17  | pub struct Graph {
    | ---------------- method `maybe_add_to_training` not found for this struct

error[E0599]: no method named `maybe_add_to_test` found for struct `Graph` in the current scope
   --> src/scenarios/dating_prob2.rs:155:29
    |
155 |                 model.graph.maybe_add_to_test(is_test, &jack_dates_jill)?;
    |                             ^^^^^^^^^^^^^^^^^ method not found in `Graph`
    |
   ::: src/common/graph.rs:17:1
    |
17  | pub struct Graph {
    | ---------------- method `maybe_add_to_test` not found for this struct

error[E0599]: no method named `get_training_questions` found for reference `&Graph` in the current scope
  --> src/common/run.rs:22:30
   |
22 |     let propositions = graph.get_training_questions()?;
   |                              ^^^^^^^^^^^^^^^^^^^^^^ method not found in `&Graph`