error[E0382]: borrow of moved value: `weight_vector`    --> src/model/maxent.rs:148:43     | 135 |         let weight_vector = match read_weights(     |             ------------- move occurs because `weight_vector` has type `HashMap<std::string::String, f64>`, which does not implement the `Copy` trait ... 145 |         weight_vectors.push(weight_vector);     |                             ------------- value moved here ... 148 |         let potential = compute_potential(&weight_vector, &features[class_label]);     |                                           ^^^^^^^^^^^^^^ value borrowed here after move