the problem is that "is" is still kicking around instead of predication
greg@Gregs-MacBook-Pro-2 node % ./dotrain.sh
[AsyncFunction: GetPropositionProbability] {
  "searchString": "[object=lonely, relation=is, subject=jack0]"
}
/Users/greg/Code/bayes_star/node/model/maxent.js:40
    const r = record.probability
                     ^

TypeError: Cannot read properties of null (reading 'probability')
    at GetPropositionProbability (/Users/greg/Code/bayes_star/node/model/maxent.js:40:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FeaturesFromBacklinks (/Users/greg/Code/bayes_star/node/model/maxent.js:72:29)
    at async TrainOnExample (/Users/greg/Code/bayes_star/node/model/maxent.js:140:22)
    at async main (/Users/greg/Code/bayes_star/node/model/train.js:20:9)

Node.js v21.1.0