i think i found the reason
test_Jack9]), underlying_hash: 4381670204457148533 }, outcome: 0
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/inference/inference.rs:240:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:775:21
   4: bayes_star::inference::inference::Inferencer::pi_compute_group
             at ./src/inference/inference.rs:237:30
   5: bayes_star::inference::inference::Inferencer::pi_compute_generic
             at ./src/inference/inference.rs:183:17
   6: bayes_star::inference::inference::Inferencer::pi_visit_node
             at ./src/inference/inference.rs:135:13
   7: bayes_star::inference::inference::Inferencer::pi_visit_node
             at ./src/inference/inference.rs:161:13
   8: bayes_star::inference::inference::Inferencer::send_pi_messages
             at ./src/inference/inference.rs:116:13
   9: bayes_star::inference::inference::Inferencer::initialize
             at ./src/inference/inference.rs:69:9
  10: bayes_star::inference::inference::inference_compute_marginals
             at ./src/inference/inference.rs:340:5
  11: bayes_star::common::test::do_testing