error[E0061]: this method takes 2 arguments but 1 argument was supplied   --> src/bin/plot.rs:30:24    | 30 |     let r = repl_state.set_pairs_by_name(&pairs);    |                        ^^^^^^^^^^^^^^^^^ ------ an argument of type `&mut redis::connection::Connection` is missing    |