[2024-01-04T17:18:11Z TRACE bayes_star::model::choose] Extracted mapping for term 0: {"object": Variable(VariableArgument { domain: Jill }), "subject": Variable(VariableArgument { domain: Jack })} [2024-01-04T17:18:11Z DEBUG bayes_star::model::ops] Converting to proposition: Proposition { roles: [FilledRole { role_name: "subject", argument: Variable(VariableArgument { domain: Jack }) }, FilledRole { role_name: "relation", argument: Constant(ConstantArgument { domain: Verb, entity_id: "like" }) }, FilledRole { role_name: "object", argument: Variable(VariableArgument { domain: Jill }) }] } [2024-01-04T17:18:11Z DEBUG bayes_star::model::ops] Processing role: FilledRole { role_name: "subject", argument: Variable(VariableArgument { domain: Jack }) } [2024-01-04T17:18:11Z DEBUG bayes_star::model::ops] Role is a variable, attempting substitution. [2024-01-04T17:18:11Z DEBUG bayes_star::model::ops] Substitution found for role: subject, substitute: Variable(VariableArgument { domain: Jack }) [2024-01-04T17:18:11Z DEBUG bayes_star::model::ops] New role after substitution: FilledRole { role_name: "subject", argument: Variable(VariableArgument { domain: Jack }) } thread 'main' panicked at 'After substitution, arg must be a constant in new_role: FilledRole { role_name: "subject", argument: Variable(VariableArgument { domain: Jack }) }', src/model/ops.rs:45:21 stack backtrace:    0: rust_begin_unwind