error[E0063]: missing field `namespace` in initializer of `InferenceGraph`   --> src/common/graph.rs:35:21    | 35 |         Ok(Box::new(InferenceGraph { redis_connection }))    |                     ^^^^^^^^^^^^^^ missing `namespace`
error[E0063]: missing field `namespace` in initializer of `InferenceGraph`
  --> src/common/graph.rs:40:20
   |
40 |         Ok(Rc::new(InferenceGraph { redis_connection }))
   |                    ^^^^^^^^^^^^^^ missing `namespace`