error[E0597]: `model` does not live long enough   --> src/common/run.rs:61:36    | 61 |     let train_result = do_training(model.borrow_mut(), &storage);    |                                    ^^^^^^^^^^^^^^^^^^ borrowed value does not live long enough ... 69 | }    | -    | |    | `model` dropped here while still borrowed    | borrow might be used here, when `model` is dropped and runs the destructor for type `Box<dyn LogicalModel>`