error[E0599]: no method named `get_proposition_probability` found for mutable reference `&mut GraphicalModel` in the current scope   --> src/model/inference.rs:29:23    | 29 |         match storage.get_proposition_probability(term) {    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `&mut GraphicalModel`    |    = help: items from traits can only be used if the trait is implemented and in scope note: `FactDB` defines an item `get_proposition_probability`, perhaps you need to implement it   --> src/common/interface.rs:16:1    | 16 | pub trait FactDB {    | ^^^^^^^^^^^^^^^^ help: one of the expressions' fields has a method of the same name    | 29 |         match storage.fact_db.get_proposition_probability(term) {    |                       ++++++++
error[E0599]: no method named `get_proposition_probability` found for mutable reference `&mut GraphicalModel` in the current scope
  --> src/model/inference.rs:62:23
   |
62 |         match storage.get_proposition_probability(term) {
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `&mut GraphicalModel`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
note: `FactDB` defines an item `get_proposition_probability`, perhaps you need to implement it
  --> src/common/interface.rs:16:1
   |
16 | pub trait FactDB {
   | ^^^^^^^^^^^^^^^^
help: one of the expressions' fields has a method of the same name
   |
62 |         match storage.fact_db.get_proposition_probability(term) {
   |                       ++++++++

error[E0063]: missing field `fact_db` in initializer of `GraphicalModel`
  --> src/common/model.rs:28:12
   |
28 |         Ok(GraphicalModel {