need to remove FactorContext
error: expected `;`, found keyword `self`
   --> src/inference/inference.rs:158:58
    |
158 |         let prediction = self.model.model.predict(factor)
    |                                                          ^ help: add `;` here
159 |         self.data.set_pi_value(from_node, 1, sum_true);
    |         ---- unexpected token

error[E0425]: cannot find value `factor` in this scope
   --> src/inference/inference.rs:158:51
    |
158 |         let prediction = self.model.model.predict(factor)
    |                                                   ^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `bayes-star` due to 2 previous errors
cargo check failed, aborting script.
greg@Gregs-MacBook-Pro-2 rust %