implementing role but need to implement argument
error[E0599]: no method named `search_string` found for enum `objects::FirstOrderArgument` in the current scope
  --> src/model/objects.rs:71:56
   |
43 | pub enum FirstOrderArgument {
   | --------------------------- method `search_string` not found for this enum
...
71 |         format!("{}={}", self.role_name, self.argument.search_string())
   |                                                        ^^^^^^^^^^^^^ method not found in `objects::FirstOrderArgument`