error[E0594]: cannot assign to data in an index of `HashMap<std::string::String, Entity>`   --> src/scenarios/dating_prob2.rs:63:13    | 63 |             domain_entity_map[&domain.to_string()] = entity;    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot assign    |    = help: trait `IndexMut` is required to modify indexed content, but it is not implemented for `HashMap<std::string::String, Entity>` help: to modify a `HashMap<std::string::String, Entity>`, use `.get_mut()`, `.insert()` or the entry API    | 63 |             domain_entity_map.insert(&domain.to_string(), entity);    |                              ~~~~~~~~                   ~       + 63 |             domain_entity_map.get_mut(&domain.to_string()).map(|val| { *val = entity; });    |                              ~~~~~~~~~                   ~~~~~~~~~~~~~~~~~~         ++++ 63 |             let val = domain_entity_map.entry(&domain.to_string()).or_insert(entity);    |             +++++++++                  ~~~~~~~                   ~~~~~~~~~~~~      +
error[E0507]: cannot move out of index of `HashMap<std::string::String, Entity>`
  --> src/scenarios/dating_prob2.rs:66:27
   |
66 |         let jack_entity = domain_entity_map[&Domain::Jack.to_string()];
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                           |
   |                           move occurs because value has type `Entity`, which does not implement the `Copy` trait
   |                           help: consider borrowing here: `&domain_entity_map[&Domain::Jack.to_string()]`

error[E0507]: cannot move out of index of `HashMap<std::string::String, Entity>`
  --> src/scenarios/dating_prob2.rs:67:27
   |
67 |         let jill_entity = domain_entity_map[&Domain::Jill.to_string()];
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                           |
   |                           move occurs because value has type `Entity`, which does not implement the `Copy` trait
   |                           help: consider borrowing here: `&domain_entity_map[&Domain::Jill.to_string()]`